### ISSUE TITLE
supporting other mermaid types than graph

### ISSUE THREAD

**Issue by rishigoutam** [maiermic/reveal-md-mermaid-animation-example#3]
Hi, thank you for creating this!

I was trying to animate a [mermaid flowchart](https://mermaid-js.github.io/mermaid/#/flowchart) and noticed it did not work as expected. A simple workaround was to write the flowchart as a graph. Hence, this might be a non-issue, but there might be others looking to animate various mermaid chart types so I wanted to post.

I wrote my markdown like so. Note that I used CAPS for the graph nodes--this is because lower case letters are cut off by the CSS, but that is a separate issue.

<pre>
```mermaid
graph LR
    classDef start stroke-dasharray: 5 5
    classDef input stroke:#FFF,stroke-width:1px, fill:darkslateblue;
    classDef output stroke:#FFF,stroke-width:2px, fill:teal;

    START([START]):::start-->MARKDOWN[/"🔤 MARKDOWN"/]:::input-->PYPANDOC[["🐍 PANDOC"]]-->HTML[/"🙌 HTML"/]:::output
    PYPANDOC-->PDF[/"✨ PDF"/]:::output
    PYPANDOC-->DOCX[/"📄 DOCX"/]:::output
```
</pre>

<pre>
```mermaid-animation
START 
START-->MARKDOWN MARKDOWN
MARKDOWN-->PYPANDOC PYPANDOC
PYPANDOC-->HTML HTML
PYPANDOC-->PDF PDF
PYPANDOC-->DOCX DOCX
```
</pre>

<div align="center"><i>By adding some additional reveal-md slides, we can render the following animation</i></div>

<p align="center"> <img src="https://user-images.githubusercontent.com/1731708/162579222-3904b695-621b-43b2-af67-761bb08b1928.gif" /></p>

<div align="center">Note that the GIF quality is low. The animation is smoother locally</div>

**Comment by maiermic** [comment]
> I was trying to animate a [mermaid flowchart](https://mermaid-js.github.io/mermaid/#/flowchart) and noticed it did not work as expected.

@rishigoutam Thank you for creating this issue. Please add the code of the flowchart that you tried to animate. What did you expect? What was the actual behaviour? Are there any errors logged in the console?

**Comment by rishigoutam** [comment]
I expected the animation to be the same as with the graph. However, it looks like there is an error with the first animation step and `mermaid-animation` is not parsed in the same manner as with the graph. Console logs below

Output is these two slides/frames:
<img width="728" alt="Screen Shot 2022-04-09 at 8 14 15 AM" src="https://user-images.githubusercontent.com/1731708/162580147-ad75c35b-f019-41ef-8cb1-60b6a8483534.png">
<img width="726" alt="Screen Shot 2022-04-09 at 8 14 27 AM" src="https://user-images.githubusercontent.com/1731708/162580154-d3f8aea2-cd6a-480d-85d5-76c44ba11e1c.png">

Here is the stripped down flowchart code for repro (I believe it is identical in structure to the above example. Only `graph` has been replaced with `flowchart`):
<pre>
```mermaid
flowchart LR
    START-->MARKDOWN-->PYPANDOC-->HTML
    PYPANDOC-->PDF
    PYPANDOC-->DOCX
```

```mermaid-animation
START 
START-->MARKDOWN MARKDOWN
MARKDOWN-->PYPANDOC PYPANDOC
PYPANDOC-->HTML HTML
PYPANDOC-->PDF PDF
PYPANDOC-->DOCX DOCX
```
</pre>


Console logs:
<pre>
Uncaught Error: Could not find edgePath: start=START end=MARKDOWN
    at findEdgePathElement (reveal-mermaid-animation.js:34:13)
    at attachAnimationsFromCodeBlockDefinition (reveal-mermaid-animation.js:141:13)
    at EventTarget.attachAnimations (reveal-mermaid-animation.js:178:7)
    at reveal-mermaid.js:36:21
    at HTMLCollection.forEach (<anonymous>)
    at asyncMermaidRender (reveal-mermaid.js:12:10)
    at HTMLDivElement.<anonymous> (reveal-mermaid.js:8:43)
    at Q (reveal.js:609:10)
    at reveal.js:209:4
</pre>

**Comment by rishigoutam** [comment]
A simpler example shows the exact same issue

<pre>
```mermaid
flowchart LR
    A-->B
```

```mermaid-animation
A
A-->B B
```
</pre>

**Comment by maiermic** [comment]
I had a look. `graph` and `flowchart` render differently. I can identify the edges, but the rendered edge labels of `flowchart` are missing the information, to which nodes/edge they belong. There are no classes like `#L-L-${startNode}-${endNode}` added to the element. mermaid.js would have to add this information (classes to the elements), so that they can be identified and animated.

**Comment by rishigoutam** [comment]
Thank you for looking into it. The workaround of just using a `graph` in lieu of a `flowchart` is pretty simple, so I'll stick with that
